image:
  file: .gitpod.dockerfile

ports:
# Web UI (static resources)
- port: 3000
# Server (API, must be public for CORS)
- port: 8080
  visibility: public
  onOpen: ignore
# Test report
- port: 8081
# Java debugging
- port: 5005
  onOpen: ignore
# PostgreSQL
- port: 5432
  onOpen: ignore
# Elasticsearch
- port: 9200
  onOpen: ignore
- port: 9300
  onOpen: ignore
# NodeJS debugging
- port: 9229
  onOpen: ignore

tasks:
- init: |
    # Build all components
    yarn --cwd cli
    yarn --cwd webui
    yarn --cwd webui build:default
    server/gradlew -p server assemble downloadTestExtensions

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - richardwillis.vscode-gradle
